### PR TITLE
fix the error when options is `{}` or undefined, but the prefix is undefined

### PR DESCRIPTION
**Pull request by crossskyLi**
fix the error when options is `{}` or undefined, but the prefix is undefined

### CODE REVIEW

**Comment by sxzz** [comment]
Would you please provide a reproduction about this issue you fixed.

**Comment by crossskyLi** [comment]
`import IconVue from '@element-plus/icons-vue'
IconVue(App)
`

**Comment by sxzz** [comment]
Please upgrade to latest version. I can't reproduce it.
```ts
import { createApp } from 'vue'
import icons from '@element-plus/icons-vue/global'
import App from './App.vue'

const app = createApp(App) // or .use(icons)
icons(app)
app.mount('#app')
```

**Comment by crossskyLi** [comment]
> 

If you write code like this, won't you report errors?

**Comment by sxzz** [comment]
So without reproduction, I can't give you any help.

**Comment by crossskyLi** [comment]
> > 
> 
> If you write code like this, won't you report errors?

I see you've fixed the situation I was trying to fix, at last few version
you can close my request. Thank you.

**Comment by crossskyLi** [comment]
But I think you cloud give a default value to prefix, because the code will be transformed like this.
image

when the InstallOptions is the `{}`, the code will report error

**Pull request closed without merging**
